Update e2eTests.yml

diff --git a/.github/workflows/e2eTests.yml b/.github/workflows/e2eTests.yml
--- a/.github/workflows/e2eTests.yml
+++ b/.github/workflows/e2eTests.yml
@@ -31,23 +31,14 @@ jobs:
         continue-on-error: true
         run: mvn test -DbrowserType="chrome" -DheadlessExecution="true"  -Dtest="${{ github.event.inputs.testsPath }}"
 
-      - name: log
-        run: ls target/surefire-reports/
-      - name: Publish Report
-        continue-on-error: true
+      - name: Tests Report Chrome_Linux
+        # continue-on-error: true
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Tests Report            # Name of the check run which will be created
           path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
           reporter: java-junit
-
-      # - name: Publish Test Results
-      #   uses: EnricoMi/publish-unit-test-result-action@v2
-      #   if: always()
-      #   with:
-      #     files: |
-      #       target/surefire-reports/TEST-*.xml
 
   E2E_Firefox_Windows_Test:
     runs-on: windows-latest
@@ -69,3 +60,13 @@ jobs:
       - name: Run Tests
         continue-on-error: true
         run: mvn test -DbrowserType="firefox" -DheadlessExecution="false"  -Dtest="${{ github.event.inputs.testsPath }}"
+
+      - name: Tests Report Chrome_Linux
+        # continue-on-error: true
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests Report            # Name of the check run which will be created
+          path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
+
