Update e2eTests.yml

diff --git a/.github/workflows/e2eTests.yml b/.github/workflows/e2eTests.yml
--- a/.github/workflows/e2eTests.yml
+++ b/.github/workflows/e2eTests.yml
@@ -29,13 +29,15 @@ jobs:
         continue-on-error: true
         run: mvn test -DbrowserType="chrome" -DheadlessExecution="true"  -Dtest="${{ github.event.inputs.testsPath }}"
 
-      # - name: Publish Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: Tests Report            # Name of the check run which will be created
-      #     path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
-      #     reporter: java-junit
+      - name: log
+        run: ls target/surefire-reports/
+      - name: Publish Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests Report            # Name of the check run which will be created
+          path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
+          reporter: java-junit
 
       # - name: Publish Test Results
       #   uses: EnricoMi/publish-unit-test-result-action@v2
